== 2. Описание проекта
1. Система смартфон-сервер


Смартфон: Автономная система локализации смартфона требует следующего списка спецификаций, который отличает картографию от локализации:
a) Условия записи картографических данных будут проводиться в максимально статичных условиях, прося людей не появляться и описывая траекторию над областью записи с помощью записывающей платформы (подробнее ниже).
b) Условиями тестирования для локализации будет ручной смартфон при ходьбе, подобной человеческой, ориентация ограничена видом вперед, с низкой динамикой, стабильным захватом устройства (это эквивалентно низкому размытию) и указанием на текстурированные области, когда это возможно (области без текстуры, такие как узкий вид на плоскую стену, конечно, дадут плохое решение).
c) Сцены будут ограничены двумя сценами и следующими характеристиками:
среда, похожая на кампус, и здание.
-Площадь не будет превышать 2000 м2
-Запись будет осуществляться командой Сколтех.
-Условия освещения будут одинаковыми для разных сцен.
-Для локализации будет контролироваться динамика сцены: некоторое количество людей будет разрешено, но большое количество людей (>20 на изображении) приведет к тому, что система локализации, скорее всего, не сработает.
- В раздел документации (1.9) будет включено руководство по созданию и обработке новой сцены.
d) Решение для локализации будет представлять собой 3D-позу, которая позже будет спроецирована в 2D-пространство для визуализации приложения.

Мобильное устройство локализации: смартфон Samsung s20 (или другие эквивалентные доступные смартфоны высокого класса по предложению Navigine), работающий на автономном решении локализации со встроенными датчиками.
Картографическая платформа: требует записи данных с мобильного телефона, включая RGB видео со смартфона плюс камера глубины Azure Kinect DK. Эта сеть датчиков требует синхронизации времени через микроконтроллер (MCU). См. рисунок 1.

